[build]
target = "wasm32-unknown-emscripten"

[target.wasm32-unknown-emscripten]
rustflags = [
    "-C",
    "link-arg=-s",
    "-C",
    "link-arg=USE_GLFW=3",
    # "-C",
    # "link-arg=-s",
    # "-C",
    # "link-arg=FULL_ES2",
    "-C",
    "link-arg=-s",
    "-C",
    "link-arg=FULL_ES3",
    "-C",
    "link-arg=-s",
    "-C",
    "link-arg=USE_SDL=2",
    "-C",
    "link-arg=-s",
    "-C",
    "link-arg=MAX_WEBGL_VERSION=2 ",
    "-C",
    "link-arg=-s",
    "-C",
    "link-arg=MIN_WEBGL_VERSION=2",
    "-C",
    "link-arg=-s",
    "-C",
    "link-arg=DISABLE_DEPRECATED_FIND_EVENT_TARGET_BEHAVIOR=1", # i have no idea why i have this
    # "-C",
    # "link-arg=-s",
    # "-C",
    # "link-arg=ASSERTIONS", # for debugging only

    "-C",
    "link-arg=-s",
    "-C",
    "link-arg=ERROR_ON_UNDEFINED_SYMBOLS=0", # for ignoring some egl symbols. maybe needed for wgpu 
]
