[target.wasm32-unknown-emscripten]
rustflags = [
    "-C",
    "link-arg=-s",
    "-C",
    "link-arg=USE_GLFW=3",
    "-C",
    "link-arg=-s",
    "-C",
    "link-arg=FULL_ES2",
    "-C",
    "link-arg=-s",
    "-C",
    "link-arg=FULL_ES3",
    "-C",
    "link-arg=-s",
    "-C",
    "link-arg=USE_SDL=2",
    "-C",
    "link-arg=-s",
    "-C",
    "link-arg=MAX_WEBGL_VERSION=2 ",
    "-C",
    "link-arg=-s",
    "-C",
    "link-arg=MIN_WEBGL_VERSION=2",
    "-C",
    "link-arg=-s",
    "-C",
    "link-arg=DISABLE_DEPRECATED_FIND_EVENT_TARGET_BEHAVIOR=1",

]
